import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

test('tempo personalizado → ESP exportável → áudio → vitória automática → ranking da arena', async ({ page, browser }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => {
    const original = AudioContext.prototype.createOscillator;
    (window as unknown as { audioNotes: number }).audioNotes = 0;
    AudioContext.prototype.createOscillator = function () {
      const oscillator = original.call(this);
      const start = oscillator.start.bind(oscillator);
      oscillator.start = (when?: number) => { (window as unknown as { audioNotes: number }).audioNotes++; start(when); };
      return oscillator;
    };
  });
  const notes = () => page.evaluate(() => (window as unknown as { audioNotes: number }).audioNotes);
  const dir = join(tmpdir(), 'conep-customization-qa'); mkdirSync(dir, { recursive: true });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Escolha sua arena.' })).toBeVisible();
  const session = await page.evaluate(() => JSON.parse(Object.entries(localStorage).find(([key]) => key.startsWith('sb-') && key.endsWith('-auth-token'))![1]));
  const db = createClient(process.env.VITE_SUPABASE_URL!, process.env.VITE_SUPABASE_PUBLISHABLE_KEY!);
  await db.auth.setSession(session);
  const outsider = createClient(process.env.VITE_SUPABASE_URL!, process.env.VITE_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
  const otherAuth = await outsider.auth.signInAnonymously(); expect(otherAuth.error).toBeNull();
  await page.getByLabel('Nome da arena').fill('QA customização Voltage');
  await page.getByRole('button', { name: 'Criar arena', exact: true }).click();
  await expect(page).toHaveURL(/\/testes\/[0-9a-f-]{36}$/);
  const id = page.url().split('/').at(-1)!;
  console.log('QA cleanup', JSON.stringify({ arena: id, users: [session.user.id, otherAuth.data.user!.id] }));
  const publicContext = await browser.newContext();
  try {
    await page.getByRole('button', { name: /Configurar ESP32/ }).click();
    await expect(page.getByRole('heading', { name: 'Conecte a energia à pista.' })).toBeVisible();
    await page.getByLabel('Nome do Wi-Fi (SSID)').fill('QA "rede"');
    await page.getByLabel('Senha do Wi-Fi').fill('senha-qa\\teste');
    await page.getByRole('button', { name: 'Gerar token Player 1', exact: true }).click();
    await page.getByLabel('Pino ADC · Player 1').selectOption('32');
    const downloaded = page.waitForEvent('download');
    await page.getByRole('button', { name: '↓ Baixar config.h · Player 1', exact: true }).click();
    const download = await downloaded; expect(download.suggestedFilename()).toBe('config.h');
    const config = readFileSync((await download.path())!, 'utf8');
    expect(config).toContain(`TESTE_ID = "${id}"`); expect(config).toContain('PINO_ADC = 32');
    expect(config).toContain('PLAYER_ID = 1'); expect(config).toContain('QA \\"rede\\"');
    expect(config).toContain('senha-qa\\\\teste');
    const configured = await db.rpc('dispositivos_configurados', { p_teste_id: id }); expect(configured.data).toEqual([1]);
    expect((await outsider.rpc('dispositivos_configurados', { p_teste_id: id })).error?.code).toBe('PT403');
    await page.getByRole('button', { name: 'Substituir token Player 1', exact: true }).click();
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
    expect((await db.rpc('dispositivos_configurados', { p_teste_id: id })).data).toEqual([1]);
    await page.screenshot({ path: join(dir, 'esp-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: join(dir, 'esp-mobile.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: '▶ Jogar', exact: true }).click();
    await page.getByLabel('Tempo personalizado (segundos)').fill('14');
    await expect(page.getByRole('button', { name: /Iniciar corrida/ })).toBeDisabled();
    const invalid = await db.rpc('iniciar_corrida', { p_teste_id: id, p_modo: 'treino', p_rodada_esperada: 1, p_duracao_segundos: 601 });
    expect(invalid.error?.code).toBe('PT400');
    await page.getByLabel('Tempo personalizado (segundos)').fill('17');
    await expect(page.locator('.race-clock strong')).toHaveText('00:17');
    await page.getByRole('button', { name: /Treino no teclado/ }).click();
    await page.getByRole('button', { name: /Iniciar corrida/ }).click();
    await expect(page.locator('.race-stage')).toHaveClass(/phase-countdown/);
    await expect(page.getByLabel('Tempo personalizado (segundos)')).toBeDisabled();
    await expect(page.locator('.race-stage')).toHaveClass(/phase-running/);
    const state = await db.from('testes').select('*').eq('id', id).single();
    expect(state.data.duracao_segundos).toBe(17);
    expect(Date.parse(state.data.corrida_fim) - Date.parse(state.data.corrida_inicio)).toBe(17000);
    await page.getByRole('button', { name: 'L · Pisada forte', exact: true }).click();
    await expect(page.getByLabel('Pisadas Player 2', { exact: true })).toHaveText('1');
    expect(await notes()).toBeGreaterThan(2);
    await page.getByRole('button', { name: 'Silenciar efeitos sonoros', exact: true }).click();
    await page.waitForTimeout(200);
    const silentNotes = await notes();
    await page.getByRole('button', { name: 'A · Pisada leve', exact: true }).click();
    await expect(page.getByLabel('Pisadas Player 1', { exact: true })).toHaveText('1');
    expect(await notes()).toBe(silentNotes);
    await page.getByRole('button', { name: 'Ativar efeitos sonoros', exact: true }).click();
    await page.getByRole('button', { name: 'L · Pisada forte', exact: true }).click();
    await expect(page.getByLabel('Pisadas Player 2', { exact: true })).toHaveText('2');
    await page.screenshot({ path: join(dir, 'race-desktop.png'), fullPage: true });
    const modal = page.getByRole('dialog');
    await expect(modal).toBeVisible({ timeout: 30_000 });
    await expect(modal.getByRole('heading', { name: 'PLAYER 2 VENCEU!' })).toBeVisible();
    await expect(modal.getByLabel('Nome do vencedor')).toBeFocused();
    const result = await db.from('rodadas').select('*').eq('teste_id', id).single();
    expect(result.data.resultado.duracao_segundos).toBe(17);
    expect(result.data.resultado.elegivel_arena).toBe(true); expect(result.data.resultado.elegivel_ranking).toBe(false);
    expect((await db.rpc('registrar_vencedor', { p_rodada_id: result.data.id, p_nome: 'QA World denied' })).error?.code).toBe('PT403');
    expect((await outsider.rpc('registrar_vencedor_arena', { p_rodada_id: result.data.id, p_nome: 'Outro', p_publicar_mundial: false })).error?.code).toBe('PT403');
    await page.keyboard.press('Escape'); await expect(modal).not.toBeVisible();
    await page.getByRole('button', { name: 'Registrar meu nome', exact: true }).click(); await expect(modal).toBeVisible();
    await modal.getByLabel('Nome do vencedor').fill('QA Campeao Arena');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: join(dir, 'victory-mobile.png'), fullPage: true });
    expect(await modal.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await modal.getByRole('button', { name: 'Salvar no ranking da arena', exact: true }).click();
    await expect(modal.getByText('QA Campeao Arena, sua vitória está no ranking da arena!')).toBeVisible();
    const duplicate = await db.rpc('registrar_vencedor_arena', { p_rodada_id: result.data.id, p_nome: 'QA Campeao Arena', p_publicar_mundial: false }); expect(duplicate.error).toBeNull();
    const rename = await db.rpc('registrar_vencedor_arena', { p_rodada_id: result.data.id, p_nome: 'QA Outro', p_publicar_mundial: false }); expect(rename.error?.code).toBe('PT409');
    const publicDb = createClient(process.env.VITE_SUPABASE_URL!, process.env.VITE_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
    expect((await publicDb.from('ranking_arena').select('*').eq('rodada_id', result.data.id)).data).toHaveLength(1);
    expect((await publicDb.from('ranking_arena').insert({ teste_id: id, rodada_id: result.data.id, nome: 'Fraude' })).error).not.toBeNull();
    await modal.getByRole('button', { name: 'Voltar à arena', exact: true }).click();
    await page.getByRole('button', { name: '★ Ranking da arena', exact: true }).click();
    await page.getByLabel('Categoria', { exact: true }).selectOption('treino');
    await page.getByLabel('Duração no ranking').selectOption('17');
    await expect(page.locator('.arena-leaderboard tbody tr')).toContainText('QA Campeao Arena');
    await page.screenshot({ path: join(dir, 'ranking-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: '▶ Jogar', exact: true }).click();
    await page.getByRole('button', { name: '15s', exact: true }).click();
    await page.getByRole('button', { name: /Iniciar corrida/ }).click();
    await expect(page.locator('.race-stage')).toHaveClass(/phase-running/);
    await page.getByRole('button', { name: 'S · Pisada forte', exact: true }).click();
    await expect(page.getByLabel('Pisadas Player 1', { exact: true })).toHaveText('1');
    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 25_000 });
    await expect(page.getByRole('dialog').getByRole('heading', { name: 'PLAYER 1 VENCEU!' })).toBeVisible();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: join(dir, 'victory-desktop.png'), fullPage: true });
    expect(errors).toEqual([]);
  } finally { await db.auth.signOut(); await outsider.auth.signOut(); await publicContext.close(); }
});
