import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';

test('personalização altera a prévia, preserva a partida e mantém preferências e sons', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.addInitScript(() => {
    const audioWindow = window as Window & { playedSounds?: number[] };
    audioWindow.playedSounds = [];
    const start = AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start = function (...args: Parameters<typeof start>) {
      if (this.buffer) audioWindow.playedSounds!.push(this.buffer.duration);
      start.apply(this, args);
    };
  });
  const sounds = () => page.evaluate(() => (window as Window & { playedSounds: number[] }).playedSounds.length);
  const directory = `${process.env.TEMP}/conep-crossy-qa`;
  mkdirSync(directory, { recursive: true });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Mover galinha para frente' })).toBeVisible();
  await page.keyboard.press('Space');
  await expect(page.getByLabel('Pontuação')).toHaveText('1');
  await expect.poll(sounds).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Personalizar personagem' }).click();
  const dialog = page.getByRole('dialog');
  const preview = page.getByLabel('Prévia 3D do personagem');
  await expect(dialog).toBeVisible();
  await expect(page.getByRole('button', { name: 'Galinha', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.character-preview figcaption')).toHaveText('Galinha');
  // Allow the asynchronous preview renderer to produce its first frame.
  await expect.poll(() => preview.evaluate(canvas => (canvas as HTMLCanvasElement).width)).toBeGreaterThan(300);
  const originalPreview = await preview.screenshot();
  await page.getByRole('button', { name: 'Bacon', exact: true }).click();
  await expect(page.locator('.character-preview figcaption')).toHaveText('Bacon');
  expect((await preview.screenshot()).equals(originalPreview)).toBe(false);
  await page.getByRole('button', { name: 'Azul', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Azul', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('Space');
  await expect(page.getByLabel('Pontuação')).toHaveText('1');
  await page.screenshot({ path: `${directory}/customization-desktop.png` });
  const beforeSample = await sounds();
  await page.getByRole('button', { name: 'Testar som' }).click();
  await expect.poll(sounds).toBeGreaterThan(beforeSample);
  await page.getByLabel('Sons do jogo').fill('0');
  await expect(page.getByRole('button', { name: 'Testar som' })).toBeDisabled();
  const beforeMute = await sounds();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Mover galinha para frente' }).click();
  await expect(page.getByLabel('Pontuação')).toHaveText('2');
  expect(await sounds()).toBe(beforeMute);
  await page.reload();
  await expect(page.getByRole('button', { name: 'Mover galinha para frente' })).toBeVisible();
  await page.getByRole('button', { name: 'Personalizar personagem' }).click();
  await expect(page.getByRole('button', { name: 'Bacon', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: 'Azul', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Sons do jogo')).toHaveValue('0');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Restaurar padrão' }).click();
  await expect(page.getByRole('button', { name: 'Galinha', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Sons do jogo')).toHaveValue('60');
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: `${directory}/customization-mobile.png` });
  await page.getByRole('button', { name: 'Fechar', exact: true }).click();
  await page.getByRole('button', { name: 'Mover galinha para frente' }).click();
  await expect(page.getByLabel('Pontuação')).toHaveText('1');
  await expect.poll(sounds).toBeGreaterThan(0);
  expect(errors).toEqual([]);
});
